/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class Bank { 
    constructor(public accountId?: string,
        public branchCode?: string,
        public name?: string,
        public phone?: string,
        public type?: Bank.TypeEnum) {}
}
export namespace Bank {
    export type TypeEnum = 'CHEQUE' | 'EWALLET' | 'SAVINGS' | 'TRANSMISSION' | 'wallet' | 'string';
    export const TypeEnum = {
        CHEQUE: 'CHEQUE' as TypeEnum,
        EWALLET: 'EWALLET' as TypeEnum,
        SAVINGS: 'SAVINGS' as TypeEnum,
        TRANSMISSION: 'TRANSMISSION' as TypeEnum,
        Wallet: 'wallet' as TypeEnum,
        String: 'string' as TypeEnum
    };
}
