/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Order } from "./order";


export interface Payout { 
    date: Date;
    emailAddress: string;
    emailNotify: string;
    emailSubject: string;
    fromReference: string;
    id?: string;
    bundleId?: string
    modifiedDate?: Date;
    paid: boolean;
    orders: Array<Order>
    toAccountNumber: string;
    toBankName: string;
    toBranchCode: string;
    toId: string;
    toName: string;
    toReference: string;
    toType: Payout.ToTypeEnum;
    total: number;
    createdDate: Date;
}

export namespace Payout {
    export type ToTypeEnum = 'CHEQUE' | 'EWALLET' | 'SAVINGS' | 'TRANSMISSION' | 'wallet' | 'string';
    export const ToTypeEnum = {
        CHEQUE: 'CHEQUE' as ToTypeEnum,
        EWALLET: 'EWALLET' as ToTypeEnum,
        SAVINGS: 'SAVINGS' as ToTypeEnum,
        TRANSMISSION: 'TRANSMISSION' as ToTypeEnum,
        Wallet: 'wallet' as ToTypeEnum,
        String: 'string' as ToTypeEnum
    };
}
