/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Payout } from './payout';


export interface PayoutBundle { 
    createdBy: string;
    date: Date;
    executed: boolean;
    id?: string;
    modifiedDate?: Date;
    numberOfPayouts: number;
    payoutTotalAmount: number;
    payouts: Array<Payout>;
    type: PayoutBundle.TypeEnum;
}
export namespace PayoutBundle {
    export type TypeEnum = 'SHOP' | 'MESSENGER';
    export const TypeEnum = {
        SHOP: 'SHOP' as TypeEnum,
        MESSENGER: 'MESSENGER' as TypeEnum
    };
}
